version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development

  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development

  api-gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    depends_on:
      - backend
      - frontend
